import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
mkdirSync('artifacts', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', err => errors.push(err.message));
try {
  await page.goto('http://127.0.0.1:3100');
  await page.getByRole('button', { name: 'Explore a sample circle' }).click();
  await page.getByRole('heading', { name: 'Data structures revision.' }).waitFor();
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  assert.equal(await page.locator('.candidate-card').count(), 3);
  await page.getByRole('button', { name: 'Your preferences', exact: true }).click();
  await page.getByLabel('Maximum study-space spend per person', { exact: true }).fill('350');
  await page.getByRole('button', { name: 'Save my preferences' }).click();
  await page.getByRole('heading', { name: 'Your circle is ready.' }).waitFor();
  await page.getByRole('button', { name: 'Find our options' }).click();
  await page.getByRole('button', { name: 'Count me in' }).first().click();
  await page.getByLabel('I’ll check the venue details and unresolved requirements before visiting.').check();
  await page.getByRole('button', { name: 'Confirm my pick' }).click();
  await page.getByRole('button', { name: 'Save to calendar' }).waitFor();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Save to calendar' }).click();
  const download = await downloadPromise;
  assert.equal(download.suggestedFilename(), 'sidequest.ics');
  await page.reload();
  await page.getByRole('button', { name: 'Save to calendar' }).waitFor();

  await page.getByRole('button', { name: 'New study circle', exact: true }).click();
  await page.getByLabel('Give the study session a name').fill('Friday people');
  await page.getByLabel('Your name', { exact: true }).fill('Host');
  await page.getByLabel('City', { exact: true }).fill('Pune');
  await page.getByRole('button', { name: 'Create a study circle', exact: true }).click();
  await page.getByRole('heading', { name: 'Friday people.' }).waitFor();
  const joinUrl = page.url();
  const guestContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const guest = await guestContext.newPage();
  await guest.goto(joinUrl);
  await guest.getByLabel('Your name', { exact: true }).fill('Guest');
  await guest.getByRole('button', { name: 'Join the study circle' }).click();
  await guest.getByRole('button', { name: 'Add your preferences', exact: true }).click();
  await guest.getByLabel('Maximum study-space spend per person', { exact: true }).fill('275');
  await guest.getByRole('button', { name: 'Save my preferences' }).click();
  await guest.locator('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Add your preferences', exact: true }).click();
  await page.getByLabel('Maximum study-space spend per person', { exact: true }).fill('725');
  await page.getByRole('button', { name: 'Save my preferences' }).click();
  await page.getByRole('button', { name: 'Find our options' }).click();
  await guest.getByRole('button', { name: 'Count me in' }).first().waitFor();
  assert.ok(!(await guest.locator('body').innerText()).includes('725'));
  assert.ok(await guest.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await guest.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  await guest.getByRole('button', { name: 'Count me in' }).first().click();
  await guest.getByRole('button', { name: 'Your pick', exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: demo, preference edits, voting, confirmation, calendar download, refresh, independent guest session, mobile width, no runtime errors.');
  await guestContext.close();
} finally { await browser.close(); }
